apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: mysql-pv-volume
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi