apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: prestashop
spec:
  type: NodePort
  selector:
    app: prestashop
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 30006