apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prestashop
type: Opaque
stringData:
  database_name: prestashop_db
  database_user: shop_user
  database_password: shop_password